name: Selenium Tests

on:
  schedule:
    - cron: '0 3,11,17 * * *'  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest webdriver-manager pandas

      # - name: Run Aylesbury School tests
      #   run: pytest test_AylesburyAnswers.py --tb=short --junitxml=results.xml

      # - name: Run Barton Court School tests
      #   run: pytest test_BartonCourtAnswers.py --tb=short --junitxml=results.xml

      # - name: Run King Edward School tests
      #   run: pytest test_KingEdwardAnswers.py --tb=short --junitxml=results.xml

      # - name: Run Bishop Vesseys School tests
      #   run: pytest test_BishopVesseyAnswers.py --tb=short --junitxml=results.xml

      # - name: Run Borden Grammar School tests
      #   run: pytest test_BordenGrammar.py --tb=short --junitxml=results.xml

      # - name: Run Colchester County School tests
      #   run: pytest test_ColschesterCountyAnswers.py --tb=short --junitxml=results.xml

      # - name: Run Southend School tests
      #   run: pytest test_SouthendSchoolAnswers.py --tb=short --junitxml=results.xml

      # - name: Run Shoeburyness School tests
      #   run: pytest test_ShoeburynessAnswers.py --tb=short --junitxml=results.xml

      - name: Run Southend Girls School tests
        run: pytest test_SouthendGirls.py --tb=short --junitxml=results.xml
            
      # Upload screenshots
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/*.png

      # Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.csv
