name: Selenium Tests

on:
  schedule:
    - cron: '0 3,11,17 * * *'  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get install -y libx11-dev libxcomposite-dev libxrandr-dev libgdk-pixbuf2.0-dev libgtk-3-dev
          sudo apt-get install -y libnss3 libgconf-2-4
          python -m pip install --upgrade pip
          pip install selenium pytest webdriver-manager pandas
          
      - name: Run Aylesbury School tests
        run: pytest test_AylesburyAnswers.py --tb=short --junitxml=results.xml

      - name: Run Barton Court School tests
        run: pytest test_BartonCourtAnswers.py --tb=short --junitxml=results.xml

      - name: Run King Edward School tests
        run: pytest test_KingEdwardAnswers.py --tb=short --junitxml=results.xml

      - name: Run Bishop Vesseys School tests
        run: pytest test_BishopVesseyAnswers.py --tb=short --junitxml=results.xml

      - name: Run Borden Grammar School tests
        run: pytest test_BordenGrammar.py --tb=short --junitxml=results.xml

      - name: Run Colchester County School tests
        run: pytest test_ColschesterCountyAnswers.py --tb=short --junitxml=results.xml

      - name: Run Southend School tests
        run: pytest test_SouthendSchoolAnswers.py --tb=short --junitxml=results.xml

      - name: Run Shoeburyness School tests
        run: pytest test_ShoeburynessAnswers.py --tb=short --junitxml=results.xml

      - name: Run Southend Girls School tests
        run: pytest test_SouthendGirls.py --tb=short --junitxml=results.xml

      - name: Run ST Bernards School tests
        run: pytest test_STBernards.py  --tb=short --junitxml=results.xml

      - name: Run ST Thomas School tests
        run: pytest test_STThomas.py  --tb=short --junitxml=results.xml

      - name: Run Westcliff School tests
        run: pytest test_WestcliffBoysAnswers.py  --tb=short --junitxml=results.xml

      - name: Run Westcliff Girls School tests
        run: pytest test_WestcliffGirls.py  --tb=short --junitxml=results.xml

      - name: Run Colchester Royal Grammar School tests
        run: pytest test_ColchesterRoyalGrammarAnswers.py  --tb=short --junitxml=results.xml

      - name: Run Beacons field School tests
        run: pytest test_BeaconsfieldAnswers.py  --tb=short --junitxml=results.xml
            
      # Upload screenshots
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/*.png

      # Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.csv
